"""Immutable Decimal execution-domain models and lifecycle rules."""

from pa_agent.trading.domain.errors import (
    DecimalValueError,
    LifecycleTransitionError,
    ProductContextError,
    ReconciliationEvidenceError,
    TradingDomainError,
)
from pa_agent.trading.domain.models import (
    AccountObservation,
    Balance,
    ExecutionCommand,
    Fill,
    GatewayCapabilities,
    GatewayEvidence,
    InstrumentRules,
    IsolatedMarginOrderContext,
    LifecycleEvent,
    Mode,
    OrderProjection,
    OrderState,
    OrderType,
    Position,
    ProductType,
    QuoteObservation,
    RuleObservation,
    Side,
    SpotOrderContext,
    TimeObservation,
    UsdtPerpetualOrderContext,
    decimal_from_canonical,
    decimal_to_canonical,
)

__all__ = [
    "AccountObservation",
    "Balance",
    "DecimalValueError",
    "ExecutionCommand",
    "Fill",
    "GatewayCapabilities",
    "GatewayEvidence",
    "InstrumentRules",
    "IsolatedMarginOrderContext",
    "LifecycleEvent",
    "LifecycleTransitionError",
    "Mode",
    "OrderProjection",
    "OrderState",
    "OrderType",
    "Position",
    "ProductContextError",
    "ProductType",
    "QuoteObservation",
    "ReconciliationEvidenceError",
    "RuleObservation",
    "Side",
    "SpotOrderContext",
    "TimeObservation",
    "TradingDomainError",
    "UsdtPerpetualOrderContext",
    "decimal_from_canonical",
    "decimal_to_canonical",
]
